"""
extract_embeddings.py
------------------------

Extract pretrained CNN14 embeddings for waveform windows.

This script is used by the PatchCore-style pipeline.

Important:
- No supervised fine-tuning is used.
- No classification head is used.
- No randomly initialized projection layer is used.
- Embeddings are extracted from pretrained CNN14 frontend + conv_block1-3.
- Output embeddings are 256-dimensional by default.

Expected input metadata
-----------------------
The script expects waveform metadata CSVs generated by:

    data_preprocessing/create_waveform_metadata_csv.py

For 0.2 s windows:
    outputs/sample_windows_0p2s_3class/File_split_CSVs/
        train_metadata_waveform.csv
        val_metadata_waveform.csv
        test_metadata_waveform.csv

For 0.4 s windows:
    outputs/sample_windows_0p4s_3class/File_split_CSVs/
        train_metadata_waveform.csv
        val_metadata_waveform.csv
        test_metadata_waveform.csv

Required columns:
- path        : path to .wav window
- class_name  : Class_1 / Class_2 / Class_4
- file_id     : identifier for traceability

Outputs
-------
- <output_dir>/embeddings_full/{split}/{class_name}/emb_XXXXXX.npy
- <output_dir>/indices/{split}_index.csv

Index CSV columns:
- split
- class_name
- file_id
- path
- embedding_file
- embedding_dir
- embedding_relpath

Example usage for 0.2 s windows:
    python patchcore_pipeline/01_extract_embeddings.py \
        --dataset_root outputs/sample_windows_0p2s_3class \
        --pann_checkpoint external/checkpoints/Cnn14_mAP=0.431.pth \
        --output_dir outputs/patchcore_0p2s

Example usage for 0.4 s windows:
    python patchcore_pipeline/01_extract_embeddings.py \
        --dataset_root outputs/sample_windows_0p4s_3class \
        --pann_checkpoint external/checkpoints/Cnn14_mAP=0.431.pth \
        --output_dir outputs/patchcore_0p4s
"""

from __future__ import annotations

from pathlib import Path
import argparse
import os
import random

import numpy as np
import pandas as pd
import soundfile as sf
import torch
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

from cnn14_truncated_feature_extractor import CNN14TruncatedExtractor


# =========================================================
# ARGUMENTS
# =========================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract pretrained CNN14 embeddings for PatchCore."
    )

    parser.add_argument(
        "--dataset_root",
        type=Path,
        default=Path("outputs/sample_windows_0p2s_3class"),
        help=(
            "Dataset root containing File_split_CSVs/train_metadata_waveform.csv, "
            "val_metadata_waveform.csv, and test_metadata_waveform.csv."
        ),
    )

    parser.add_argument(
        "--pann_checkpoint",
        type=Path,
        default=Path("external/checkpoints/Cnn14_mAP=0.431.pth"),
        help="Path to pretrained PANNs CNN14 checkpoint.",
    )

    parser.add_argument(
        "--output_dir",
        type=Path,
        default=Path("outputs/patchcore_0p2s"),
        help="Output directory for extracted embeddings and index files.",
    )

    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--sample_rate", type=int, default=25600)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--l2_normalize", type=int, default=1)

    return parser.parse_args()


# =========================================================
# REPRODUCIBILITY
# =========================================================
def seed_everything(seed: int = 42) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# =========================================================
# HELPERS
# =========================================================
def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def save_npy(path: Path, array: np.ndarray) -> None:
    ensure_dir(path.parent)
    np.save(path, array)


# =========================================================
# DATASET
# =========================================================
class WavRows(Dataset):
    """Read waveform windows from paths listed in a metadata CSV."""

    def __init__(self, df: pd.DataFrame, target_sr: int = 25600):
        self.df = df.reset_index(drop=True)
        self.target_sr = target_sr

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int):
        row = self.df.iloc[idx]
        wav_path = str(row["path"])

        wave, sr = sf.read(wav_path)

        if sr != self.target_sr:
            raise RuntimeError(
                f"Sample-rate mismatch in {wav_path}: got {sr}, expected {self.target_sr}"
            )

        if wave.ndim > 1:
            wave = wave.mean(axis=1)

        wave = torch.tensor(wave, dtype=torch.float32)

        return wave, idx


# =========================================================
# MAIN
# =========================================================
def main() -> None:
    args = parse_args()

    seed_everything(args.seed)

    dataset_root = args.dataset_root
    meta_dir = dataset_root / "File_split_CSVs"

    split_csvs = {
        "train": meta_dir / "train_metadata_waveform.csv",
        "val": meta_dir / "val_metadata_waveform.csv",
        "test": meta_dir / "test_metadata_waveform.csv",
    }

    pann_checkpoint = args.pann_checkpoint
    output_dir = args.output_dir

    out_embeddings = output_dir / "embeddings_full"
    out_indices = output_dir / "indices"

    ensure_dir(out_embeddings)
    ensure_dir(out_indices)

    device = "cuda" if torch.cuda.is_available() else "cpu"

    # ---------------------------------------------------------
    # Sanity checks
    # ---------------------------------------------------------
    for split, csv_path in split_csvs.items():
        if not csv_path.exists():
            raise FileNotFoundError(f"Missing {split} metadata CSV: {csv_path}")

    if not pann_checkpoint.exists():
        raise FileNotFoundError(
            f"Missing PANN checkpoint: {pann_checkpoint}\n"
            "Place Cnn14_mAP=0.431.pth under external/checkpoints/."
        )

    print("=== EMBEDDING EXTRACTION INFO ===")
    print("device:          ", device)
    print("dataset_root:    ", dataset_root)
    print("pann_checkpoint: ", pann_checkpoint)
    print("output_dir:      ", output_dir)
    print("batch_size:      ", args.batch_size)
    print("sample_rate:     ", args.sample_rate)
    print("l2_normalize:    ", bool(args.l2_normalize))
    print("=================================")

    # ---------------------------------------------------------
    # Load pretrained feature extractor
    # ---------------------------------------------------------
    model = CNN14TruncatedExtractor(
        pann_ckpt_path=pann_checkpoint,
        freeze_frontend=True,
        l2_normalize=bool(args.l2_normalize),
    ).to(device)

    model.eval()

    keep_classes = {"Class_1", "Class_2", "Class_4"}

    # ---------------------------------------------------------
    # Extract embeddings for each split
    # ---------------------------------------------------------
    with torch.no_grad():
        for split, csv_path in split_csvs.items():
            df = pd.read_csv(csv_path)

            for col in ["path", "class_name"]:
                if col not in df.columns:
                    raise ValueError(f"{csv_path} missing required column: {col}")

            if "file_id" not in df.columns:
                df["file_id"] = df["path"].map(lambda p: Path(str(p)).stem.split("_")[2])

            df = df[df["class_name"].isin(keep_classes)].reset_index(drop=True)

            dataset = WavRows(df, target_sr=args.sample_rate)

            loader = DataLoader(
                dataset,
                batch_size=args.batch_size,
                shuffle=False,
                num_workers=args.num_workers,
                pin_memory=True,
                drop_last=False,
            )

            records = []
            counters = {"Class_1": 0, "Class_2": 0, "Class_4": 0}

            print(f"\n[INFO] Split={split} | samples={len(dataset)} | csv={csv_path}")

            for wave, idx in tqdm(loader, total=len(loader)):
                wave = wave.to(device, non_blocking=True)
                embeddings = model(wave).cpu().numpy()  # shape: (B, 256)

                for row_idx, emb in zip(idx.numpy(), embeddings):
                    row = df.iloc[int(row_idx)]
                    class_name = row["class_name"]

                    class_out_dir = out_embeddings / split / class_name
                    ensure_dir(class_out_dir)

                    emb_name = f"emb_{counters[class_name]:06d}.npy"
                    counters[class_name] += 1

                    emb_path = class_out_dir / emb_name
                    save_npy(emb_path, emb)

                    emb_relpath = (
                        Path(output_dir.name)
                        / "embeddings_full"
                        / split
                        / class_name
                        / emb_name
                    )

                    records.append(
                        {
                            "split": split,
                            "class_name": class_name,
                            "file_id": row["file_id"],
                            "path": row["path"],
                            "embedding_file": emb_name,
                            "embedding_dir": str(class_out_dir),
                            "embedding_relpath": str(emb_relpath),
                        }
                    )

            index_out = out_indices / f"{split}_index.csv"
            pd.DataFrame(records).to_csv(index_out, index=False)

            print(f"[OK] Wrote index: {index_out}")
            print(f"[OK] Counts: {counters}")

    print("\n[DONE] Embedding extraction finished.")


if __name__ == "__main__":
    main()